Numpy - Numerical python


advamtages of numpy array:
1. Allow several  Mathmatical operactions
2. Faster operations

In [ ]:
import numpy as np

List vs numpy array time taken

In [ ]:
from time import process_time

time taken by a list

In [ ]:

python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i + 5 for i in python_list]

end_time = process_time()
print(end_time - start_time)

0.0005631340000000762


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()
np_array += 5
end_time = process_time()

print(end_time - start_time)

0.0006870800000000621


Numpy arrays

In [ ]:
#list
list1 =[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

creating one  1 d array

In [ ]:
a =np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

2d array

In [ ]:
b =np.array([(1,2,3,4),(5,6,7,8)])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
b.shape

(2, 4)

d.type is used to change the data type

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
c

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

intial placeholder in numpy array

In [ ]:
 #creating  a numpy array with zeros
 x = np.zeros((4,5))
 x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#creating numpy arrays of ones
y =np.ones((3,3))
y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#array with a paricular value
z =np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#creating identity matrix
a =np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#creating  a numpy array  with random  values

float values

In [37]:
#creating  a numpy array  with random  value

b =np.random.random((3,4))
b

array([[0.13981346, 0.28918061, 0.60340001, 0.62899017],
       [0.30885942, 0.81738084, 0.04318789, 0.10157583],
       [0.25216173, 0.49870223, 0.84906042, 0.37336735]])

#for integars values

In [43]:
# random integer values array within a specific range
c = np.random.randint(10, 100, (3, 5))
c


array([[48, 97, 46, 40, 58],
       [63, 93, 67, 33, 98],
       [30, 84, 27, 25, 56]])

In [46]:
#array of evenly spaced values ------>> specifying  the numbers of  values required
d =np.linspace(10,30,6)
d

array([10., 14., 18., 22., 26., 30.])

In [49]:
#array of evenly spaced values --> specifying the step
e =np.arange(10,30,5)
e

array([10, 15, 20, 25])

In [53]:
#convert a list to numpy array
list2 =[10,20,30,40,50]
np_array  =np.array(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

#analysing the numpy array

In [55]:
c =np.random.randint(10,90,(5,5))
c

array([[19, 45, 48, 76, 43],
       [84, 69, 69, 63, 18],
       [22, 83, 24, 72, 40],
       [78, 18, 66, 53, 66],
       [14, 45, 16, 44, 51]])

In [56]:
#array dimension
print(c.shape)

(5, 5)


In [57]:
c.ndim

2

In [58]:
#numbers of elements  in an array

In [59]:
c.size

25

In [60]:
#checking the data of the values in array
c.dtype

dtype('int64')

Mathmatical operaction on numpy array

In [64]:
#in list
list1 =[1,2,3,4,5]
list2 =[6,7,8,9,10]
print(list1 + list2) #Concatinate the elements or join two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [67]:
#in numpy array
a =np.random.randint(0,10,(3,3))
b =np.random.randint(10,20,(3,3))

In [68]:
print(a)
print(b)

[[0 0 3]
 [1 1 3]
 [3 8 6]]
[[11 18 17]
 [13 14 15]
 [15 16 19]]


In [71]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)

[[11 18 20]
 [14 15 18]
 [18 24 25]]
[[-11 -18 -14]
 [-12 -13 -12]
 [-12  -8 -13]]
[[  0   0  51]
 [ 13  14  45]
 [ 45 128 114]]
[[0.         0.         0.17647059]
 [0.07692308 0.07142857 0.2       ]
 [0.2        0.5        0.31578947]]
[[0 0 3]
 [1 1 3]
 [3 8 6]]


In [72]:
a =np.random.randint(0,10,(3,3))
b =np.random.randint(10,20,(3,3))

In [73]:
print(a)
print(b)

[[0 8 3]
 [5 9 7]
 [4 9 8]]
[[11 16 10]
 [16 10 13]
 [17 10 10]]


In [75]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[11 24 13]
 [21 19 20]
 [21 19 18]]
[[-11  -8  -7]
 [-11  -1  -6]
 [-13  -1  -2]]
[[  0 128  30]
 [ 80  90  91]
 [ 68  90  80]]
[[0.         0.5        0.3       ]
 [0.3125     0.9        0.53846154]
 [0.23529412 0.9        0.8       ]]


array manipulation

In [76]:
array =np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 7 6]
 [8 2 6]]
(2, 3)


In [77]:
#transpose
trans =np.transpose(array)
print(trans)
print(trans.shape)

[[5 8]
 [7 2]
 [6 6]]
(3, 2)


In [78]:
array =np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 4 5]
 [7 9 6]]
(2, 3)


In [80]:
trans2 =array.T
print(trans2)
print(trans2.shape)

[[7 7]
 [4 9]
 [5 6]]
(3, 2)


In [82]:
#reshaping the array
a  =np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[3 0 4]
 [1 7 5]]
(2, 3)


In [83]:
b =a.reshape(3,2)
print(b)
print(b.shape)

[[3 0]
 [4 1]
 [7 5]]
(3, 2)
